package Enums;

public enum NotificationType {
	RESERVED_APPOINTMENT, COMMENT, REFERRAL, PROMO_CODE, FAVORITE, APPOINTMENT_STATUS, APPOINTMENT_RESULT,
	APPOINTMENT_PRESCRIPTION, FREE_APPOINTMENT, APPOINTMENT_REMINDER
}
